version: '3'
services:
  mongodb:
      image: mongo
      volumes:
        - ./dockercompose/mongo/data:/data/db
      command: mongod  --logpath=/dev/null # --quiet
      ports:
        - "27017:27017"

  performance-test-mongo-server:
    depends_on: [ "mongodb"]
    build: dockercompose/performance-test-java-mongo
    ports:
     - "1403:1403"
    environment:
      SPRING_DATA_MONGODB_URI: "mongodb://mongo:27017/test?serverSelectionTimeoutMS=2000&connectTimeoutMS=2000"
    volumes:
     - ./dockercompose/performance-test-java-mysql/app.jar:/home/app.jar

  prometheus:
    image: prom/prometheus:latest
    container_name: monitoring_prometheus
    restart: unless-stopped
    volumes:
      - ./dockercompose/prometheus/config:/etc/prometheus/
      - ./dockercompose/prometheus/data:/prometheus
    expose:
      - 9090
    ports:
      - 9090:9090
    links:
      - performance-test-mongo-server:performance-test-mongo-server
      - mongodb:mongodb